# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot
org.gradle.parallel=true

# Mod properties
mod_version = 2.6.2
maven_group = com.denisnumb.discord_chat_mod
archives_name = discord_chat_mod
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.145.1+26.1
neoforge_version = 26.1.0.19-beta
